# Generated by Django 4.0.5 on 2022-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shu',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
